#!/bin/sh

#
# Umount all
#
if [ $(mount | grep -c ${DISK}1) -eq 1 ]; then
    sudo umount ${DISK}1
    echo "umount ${DISK}1"
fi

if [ $(mount | grep -c ${DISK}2) -eq 1 ]; then
    sudo umount ${DISK}2
    echo "umount ${DISK}2"
fi

#
# Format
#
sudo mkfs.vfat -F 16 ${1}1 -n boot
sudo mkfs.ext4 ${1}2 -L rootfs

sync

if [ $(mount | grep -c ${DISK}1) -eq 1 ]; then
    sudo umount ${DISK}1
    echo "umount ${DISK}1"
fi

if [ $(mount | grep -c ${DISK}2) -eq 1 ]; then
    sudo umount ${DISK}2
    echo "umount ${DISK}2"
fi

sudo fsck -y ${1}1
sudo fsck -y ${1}2

exit 0
